name = "3rike/tricycle-nft"
version = "0.1.0"
compiler = "v1.1.22"
plutus = "v3"
license = "MIT"
description = "TricycleNFT for 3rike Mobility — Cardano Preprod testnet"

[repository]
user = "3rike"
project = "tricycle-nft"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
